### ISSUE TITLE
Website Performance is slow

### ISSUE THREAD

**Issue by mfrankwork** [caseconsulting/website#1]
The website takes a long time to load.  I have tried from home (~9 sec load time), the office (~2 sec load time), and my cell phone (> 10 sec load time).  The biggest load times are for (uncompressed) images, several of which are probably larger than needed for the website.

Reading the website on my cell phone (Safari on iOS) was particularly sluggish.  Scrolling the home page caused large white patches that were replaced with graphics after a little while.

I ran audits in Google Chrome and found the following:
![image](https://user-images.githubusercontent.com/17320311/30444283-64b8cf4a-9950-11e7-9111-3a94a5842953.png)
![image](https://user-images.githubusercontent.com/17320311/30444302-7cd27c5c-9950-11e7-990e-0159b6eb8470.png)
![image](https://user-images.githubusercontent.com/17320311/30444316-8b25e528-9950-11e7-87f3-a73de65fdb90.png)
![image](https://user-images.githubusercontent.com/17320311/30444334-98e4b0ea-9950-11e7-9e37-3e4cf07d0d28.png)
![image](https://user-images.githubusercontent.com/17320311/30444344-a1a43ff2-9950-11e7-8230-aaf477d925a7.png)

**Comment by pcorrell** [comment]
I reduced the sizes of all of the images which brought down the size of the page and the load times. Per the Safari dev tools it is loading in less than 3 seconds on an empty cache. Will continue to look into other ways to improve, but this was the big one I wanted to get done.

**Comment by pcorrell** [comment]
Moved to Redmine
