### ISSUE TITLE
Update the Events section

### ISSUE THREAD

**Issue by pcorrell** [caseconsulting/website#2]
We should show all of the events on the screen and remove the carousel

**Comment by pfarmer1** [comment]
related to the bug I found where it's sometimes showing 2 events and other times showing 4 events.....do we think showing all events on the screen will lead to a really large section?  Do we maybe have some kind of a "more" option that takes you to a page with all the events but keep the event carousel??

**Comment by drewhcooper** [comment]
Changed to a deck layout

**Comment by fahada95** [comment]
Reduce the number of visible events and "show more" button

**Comment by jet3wv** [comment]
Added the pagination of events with a show more/show less button that expands and collapses the number of visible events

**Comment by jet3wv** [comment]
Need to change to 3 cards in a deck, and fix the size of the cards in the last row

**Comment by SamPeake** [comment]
Changed to 3 cards in a deck, and fixed the size of the cards in the last row.
