### ISSUE TITLE
Internship page - Requirements

### ISSUE THREAD

**Issue by pcorrell** [caseconsulting/website#33]

**Comment by pcorrell** [comment]
Technical Skills
Minimum 3.0 GPA
Majoring in Computer Science, Computer Engineering, or related field
Experience with object oriented software development
Desire to apply and develop technical skills

Collaborative Skills
Works well in team environment
Strong written and communication skills
Desire to apply and develop interpersonal skills
Likes to have fun

Other Requirements
U.S. Citizen
Ability to obtain a security clearance
Desire to work in the Northern Virginia area
Currently in Junior year

**Comment by jet3wv** [comment]
Looks good on laptop and mobile. Sprint meeting 6/25/2018
